<?php

/**
 * @author Dlani
 * @copyright 2008
 */

$this->_html .= '

		<fieldset>
			<legend><img src="../img/admin/money.gif" />Configura&ccedil;&otilde;es Banc&aacute;rias</legend>
			
			<label>N&uacute;mero da Ag&ecirc;ncia</label>			
			<div class="margin-form">
			<input type="text" size="33" name="agencia" value="" /> Num da ag&ecirc;ncia, sem digito</div>

			
			<label>N&uacute;mero da Conta</label>			
			<div class="margin-form">
			<input type="text" size="33" name="conta" value="" /> Num da conta, sem digito</div>

			
			<label>N&uacute;mero Conv&ecirc;nio</label>			
			<div class="margin-form">
			<input type="text" size="33" name="convenio" value="" /> Num do conv&ecirc;nio - REGRA: 6 ou 7 ou 8 d&iacute;gitos</div>

			
			<label>N&uacute;mero do Contrato</label>			
			<div class="margin-form">
			<input type="text" size="33" name="contrato" value="" /> Num do seu contrato</div>

			
			<label>N&uacute;mero da Carteira</label>			
			<div class="margin-form">
			<input type="text" size="33" name="carteira" value="" /> Varia&ccedil;&atilde;o da Carteira, com tra&ccedil;o (opcional)</div>

					
			<br />
			
			
		</fieldset>';

?>