<?php

/**
 * @author Dlani
 * @copyright 2008
 */

$this->_html .= '

		<fieldset>
			<legend><img src="../img/admin/translation.gif" />Instru&ccedil;&otilde;es e Informa&ccedil;&otilde;es</legend>
			
			<label>Demonstrativo 1</label>			
			<div class="margin-form">
			<input type="text" size="33" name="demonstrativo1" value="" /> </div>

			
			<label>Demonstrativo 2</label>			
			<div class="margin-form">
			<input type="text" size="33" name="demonstrativo2" value="" /> </div>

			
			<label>Demonstrativo 3</label>			
			<div class="margin-form">
			<input type="text" size="33" name="demonstrativo3" value="" /> </div>

			
			<label>Instru&ccedil;&otilde;es 1</label>			
			<div class="margin-form">
			<input type="text" size="33" name="instrucoes1" value="" /> </div>

			
			<label>Instru&ccedil;&otilde;es 2</label>			
			<div class="margin-form">
			<input type="text" size="33" name="instrucoes2" value="" /> </div>

			<label>Instru&ccedil;&otilde;es 3</label>			
			<div class="margin-form">
			<input type="text" size="33" name="instrucoes3" value="" /> </div>
			
			<label>Instru&ccedil;&otilde;es 4</label>			
			<div class="margin-form">
			<input type="text" size="33" name="instrucoes4" value="" /> </div>
					
			<br />
			
			
		</fieldset>';

?>